# SPDX-License-Identifier: MIT
# qqcandy: checked against the deployed UCM, ALSA controls and board kernel.
# Both outputs use PCM2/DL2. Do not replace these with Xaga's PCM0/DL1 route.
# AIN0 is the internal microphone; AIN1 is the headset microphone.

SectionVerb {
	EnableSequence [ cdev "hw:${CardId}" ]
	DisableSequence [ cdev "hw:${CardId}" ]
	Value { TQ "HiFi" }
}

SectionDevice."Speaker" {
	Comment "Internal speakers (NXP TFA9874)"
	Value {
		PlaybackPCM "hw:${CardId},2"
		PlaybackChannels "2"
		PlaybackPriority "100"
		PlaybackMixerElem "Lineout Volume"
	}
	ConflictingDevice [ "Headphones" ]
	EnableSequence [
		cdev "hw:${CardId}"
		cset "name='I2S3_CH1 DL2_CH1' on"
		cset "name='I2S3_CH2 DL2_CH2' on"
		cset "name='ADDA_DL_CH1 DL2_CH1' off"
		cset "name='ADDA_DL_CH2 DL2_CH2' off"
		cset "name='HPL Mux' Open"
		cset "name='HPR Mux' Open"
		cset "name='Headphone Plugged In' Off"
	]
	DisableSequence [
		cdev "hw:${CardId}"
		cset "name='I2S3_CH1 DL2_CH1' off"
		cset "name='I2S3_CH2 DL2_CH2' off"
	]
}

SectionDevice."Headphones" {
	Comment "3.5 mm headphones (MT6368)"
	Value {
		PlaybackPCM "hw:${CardId},2"
		PlaybackChannels "2"
		PlaybackPriority "200"
		PlaybackMixerElem "Lineout Volume"
		JackControl "Headphone Jack"
	}
	ConflictingDevice [ "Speaker" ]
	EnableSequence [
		cdev "hw:${CardId}"
		cset "name='ADDA_DL_CH1 DL2_CH1' on"
		cset "name='ADDA_DL_CH2 DL2_CH2' on"
		cset "name='I2S3_CH1 DL2_CH1' off"
		cset "name='I2S3_CH2 DL2_CH2' off"
		cset "name='Headphone Plugged In' On"
		cset "name='HPL Mux' 'Audio Playback'"
		cset "name='HPR Mux' 'Audio Playback'"
	]
	DisableSequence [
		cdev "hw:${CardId}"
		cset "name='HPL Mux' Open"
		cset "name='HPR Mux' Open"
		cset "name='Headphone Plugged In' Off"
		cset "name='ADDA_DL_CH1 DL2_CH1' off"
		cset "name='ADDA_DL_CH2 DL2_CH2' off"
	]
}

SectionDevice."Mic" {
	Comment "Internal microphone"
	Value {
		CapturePCM "hw:${CardId},1"
		CaptureChannels "2"
		CapturePriority "100"
	}
	ConflictingDevice [ "Headset" ]
	EnableSequence [
		cdev "hw:${CardId}"
		cset "name='UL_SRC_MUX' AMIC"
		cset "name='MISO0_MUX' UL1_CH1"
		cset "name='MISO1_MUX' UL1_CH1"
		cset "name='ADC_L_Mux' 'Left Preamplifier'"
		cset "name='PGA_L_Mux' AIN0"
	]
	DisableSequence [
		cdev "hw:${CardId}"
		cset "name='MISO1_MUX' UL1_CH2"
		cset "name='ADC_L_Mux' Idle"
		cset "name='PGA_L_Mux' None"
	]
}

SectionDevice."Headset" {
	Comment "3.5 mm headset microphone (MT6368)"
	Value {
		CapturePCM "hw:${CardId},1"
		CaptureChannels "2"
		CapturePriority "200"
		JackControl "Headset Mic Jack"
	}
	ConflictingDevice [ "Mic" ]
	EnableSequence [
		cdev "hw:${CardId}"
		cset "name='UL_SRC_MUX' AMIC"
		cset "name='MISO0_MUX' UL1_CH1"
		cset "name='MISO1_MUX' UL1_CH1"
		cset "name='ADC_L_Mux' 'Left Preamplifier'"
		cset "name='PGA_L_Mux' AIN1"
	]
	DisableSequence [
		cdev "hw:${CardId}"
		cset "name='MISO1_MUX' UL1_CH2"
		cset "name='ADC_L_Mux' Idle"
		cset "name='PGA_L_Mux' None"
	]
}
